version: '3.8'

services:
  mysql-biblioteca:
    image: mysql:8.0
    container_name: mysql-biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: biblioteca
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - biblioteca-network

volumes:
  mysql-data:
    driver: local

networks:
  biblioteca-network:
    driver: bridge

